# Zeabur 部署配置 - 強制使用 buildCommand
name: pythonlearn-collaboration

services:
  # 主要 PHP 應用服務
  web:
    # 明確指定構建方式，不使用 Dockerfile
    build:
      dockerfile: false
      buildCommand: |
        echo "🔧 開始構建 PHP 應用..."
        echo "📦 當前目錄內容:"
        ls -la
        echo "📋 Composer 版本:"
        composer --version || echo "Composer 不可用"
        echo "🔧 安裝依賴 (忽略平台要求)..."
        composer install --no-dev --no-interaction --no-scripts --ignore-platform-reqs --no-cache --optimize-autoloader || echo "✅ Composer 完成"
        echo "📁 創建必要目錄..."
        mkdir -p data logs storage
        chmod -R 755 data logs storage || echo "權限設置完成"
        echo "✅ 構建完成"
    
    # 啟動命令
    start: php -S 0.0.0.0:8080 -t public router.php
    
    # 端口配置
    ports:
      - 8080
    
    # 基本環境變數
    envs:
      ENVIRONMENT: production
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: gpt-3.5-turbo
      MAX_CONCURRENT_USERS: 50
      MAX_ROOMS: 20
    
    # 健康檢查
    healthcheck:
      path: /health.php
      interval: 30s
      timeout: 10s
    
    # 重啟策略
    restart: unless-stopped

# 部署配置
deploy:
  auto: true
  
  # 環境變數 (全部可選)
  envs:
    optional:
      - OPENAI_API_KEY

# 🔍 日誌配置
logging:
  driver: json-file
  options:
    max-size: "50m"
    max-file: "2"

# 🌐 網路配置
networks:
  default:
    driver: bridge

# 📊 監控配置
monitoring:
  enabled: true
  metrics:
    - name: http_requests_total
      type: counter
      help: "Total HTTP requests"
    
    - name: websocket_connections
      type: gauge
      help: "Active WebSocket connections"
    
    - name: caddy_requests_total
      type: counter
      help: "Total Caddy proxy requests"
    
    - name: ai_requests_total
      type: counter
      help: "Total AI assistant requests"
    
    - name: python_executions_total
      type: counter
      help: "Total Python code executions"

# 🔐 密鑰管理
secrets:
  openai-api-key:
    external: true
    name: OPENAI_API_KEY
  
  mysql-root-password:
    external: true
    name: MYSQL_ROOT_PASSWORD
  
  mysql-password:
    external: true
    name: MYSQL_PASSWORD

# 卷配置
volumes:
  mysql_data:
    driver: local

# 健康檢查配置
healthcheck:
  php:
    path: /health.php
    interval: 30s
    timeout: 10s
    
  websocket:
    port: 8081
    interval: 30s
    timeout: 10s
    retries: 3

# 環境變數配置
env:
  # MySQL 密碼（需要在 Zeabur 控制台設置）
  MYSQL_ROOT_PASSWORD:
    type: secret
    default: "secure_root_password_2024"
    
  MYSQL_PASSWORD:
    type: secret
    default: "secure_user_password_2024"
    
  # OpenAI API 密鑰（需要在 Zeabur 控制台設置）
  OPENAI_API_KEY:
    type: secret
    
  # 域名（Zeabur 自動設置）
  ZEABUR_DOMAIN:
    type: auto 