# Zeabur 部署配置 - 純 PHP 單服務架構
name: pythonlearn-php-collaboration

services:
  web:
    # 🏗️ 建構設定 - 明確指定不使用 Composer
    build:
      env: php
      command: |
        echo "🚀 純 PHP 項目構建開始..."
        echo "📦 跳過 Composer 安裝 (零依賴項目)"
        echo "✅ 構建完成 - 無需額外依賴"
    
    # 🚀 啟動指令 - 使用整合服務器
    start: php test-servers/integrated-server.php
    
    # 🌐 環境變數
    env:
      # PHP 配置
      PHP_VERSION: "8.1"
      COMPOSER_ALLOW_SUPERUSER: "1"
      
      # 應用配置
      APP_ENV: "production"
      MAX_CONCURRENT_USERS: 50
      MAX_ROOMS: 20
      MAX_USERS_PER_ROOM: 8
      
      # AI 配置 (可選)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
    
    # 🔌 端口配置 - 只使用一個端口
    ports:
      - 8080
    
    # 🏥 健康檢查
    healthcheck:
      path: /
      interval: 30s
      timeout: 10s
      retries: 3
    
    # 📊 資源配置
    resources:
      cpu: 500m      # 0.5 CPU core
      memory: 256Mi  # 256MB RAM

# 📊 監控配置
monitoring:
  enabled: true
  metrics:
    - name: http_requests_total
      type: counter
      help: "Total HTTP requests"
    
    - name: websocket_connections
      type: gauge
      help: "Active WebSocket connections"
    
    - name: ai_requests_total
      type: counter
      help: "Total AI assistant requests"

# 🔐 密鑰管理
secrets:
  openai-api-key:
    external: true
    name: OPENAI_API_KEY

# 卷配置
volumes:
  mysql_data:
    driver: local

# 健康檢查配置
healthcheck:
  web:
    path: /health.php
    interval: 30s
    timeout: 10s
    
  caddy:
    port: 80
    interval: 30s
    timeout: 10s

# 環境變數配置
env:
  # OpenAI API 密鑰（需要在 Zeabur 控制台設置）
  OPENAI_API_KEY:
    type: secret
    
  # 域名（Zeabur 自動設置）
  ZEABUR_DOMAIN:
    type: auto 