# Zeabur 部署配置 - 雙服務架構 (穩定版)
name: python-learn

services:
  # 主要 Web 服務 (PHP + WebSocket)
  web:
    build:
      dockerfile: Dockerfile.zeabur
    
    # 環境變數配置
    env:
      # WebSocket 服務器配置
      WEBSOCKET_HOST: "0.0.0.0"
      WEBSOCKET_PORT: "8081"
      
      # PHP 配置
      PHP_MEMORY_LIMIT: "256M"
      PHP_MAX_EXECUTION_TIME: "300"
      
      # 應用配置
      APP_ENV: "production"
      DEBUG_MODE: "false"
      
      # AI 配置 (從 Zeabur 環境變數)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_MAX_TOKENS: ${OPENAI_MAX_TOKENS}
      
      # 數據庫配置 (從 Zeabur 環境變數)
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
    
    # 暴露端口 (內部通信)
    ports:
      - 8080  # HTTP 服務
      - 8081  # WebSocket 服務
    
    # 健康檢查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Caddy 反向代理服務
  caddy:
    build:
      dockerfile: Dockerfile.caddy
    
    # 環境變數
    env:
      # Zeabur 會自動設置這個變數
      ZEABUR_WEB_DOMAIN: ${ZEABUR_WEB_DOMAIN}
    
    # 暴露端口 (對外服務)
    ports:
      - 80
      - 443
    
    # 依賴 web 服務
    depends_on:
      - web
    
    # 健康檢查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2019/metrics"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

# 全域配置
configs:
  # 自動重啟配置
  restart_policy:
    condition: on-failure
    max_attempts: 3
    delay: 10s
  
  # 日誌配置
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "3"

# 🌐 網路配置
networks:
  default:
    driver: bridge

# 📊 監控配置
monitoring:
  enabled: true
  metrics:
    - name: http_requests_total
      type: counter
      help: "Total HTTP requests"
    
    - name: websocket_connections
      type: gauge
      help: "Active WebSocket connections"
    
    - name: caddy_requests_total
      type: counter
      help: "Total Caddy proxy requests"
    
    - name: ai_requests_total
      type: counter
      help: "Total AI assistant requests"
    
    - name: python_executions_total
      type: counter
      help: "Total Python code executions"

# 🔐 密鑰管理
secrets:
  openai-api-key:
    external: true
    name: OPENAI_API_KEY

# 卷配置
volumes:
  mysql_data:
    driver: local

# 健康檢查配置
healthcheck:
  web:
    path: /health.php
    interval: 30s
    timeout: 10s
    
  caddy:
    port: 80
    interval: 30s
    timeout: 10s

# 環境變數配置
env:
  # OpenAI API 密鑰（需要在 Zeabur 控制台設置）
  OPENAI_API_KEY:
    type: secret
    
  # 域名（Zeabur 自動設置）
  ZEABUR_DOMAIN:
    type: auto 