# Zeabur 部署配置 - 單服務整合架構 (修復版)
name: python-learn

services:
  # 整合服務 (HTTP + WebSocket 在同一端口)
  web:
    build:
      dockerfile: Dockerfile.simple
    
    # 環境變數配置
    env:
      # 應用配置
      APP_ENV: "production"
      DEBUG_MODE: "false"
      PORT: "8080"
      
      # AI 配置 (從 Zeabur 環境變數)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_MAX_TOKENS: ${OPENAI_MAX_TOKENS}
      
      # 數據庫配置 (從 Zeabur 環境變數)
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
    
    # 暴露端口 (只有一個端口)
    ports:
      - 8080
    
    # 健康檢查
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

# 📊 監控配置
monitoring:
  enabled: true
  metrics:
    - name: http_requests_total
      type: counter
      help: "Total HTTP requests"
    
    - name: websocket_connections
      type: gauge
      help: "Active WebSocket connections"
    
    - name: ai_requests_total
      type: counter
      help: "Total AI assistant requests"

# 🔐 密鑰管理
secrets:
  openai-api-key:
    external: true
    name: OPENAI_API_KEY

# 卷配置
volumes:
  mysql_data:
    driver: local

# 健康檢查配置
healthcheck:
  web:
    path: /health.php
    interval: 30s
    timeout: 10s
    
  caddy:
    port: 80
    interval: 30s
    timeout: 10s

# 環境變數配置
env:
  # OpenAI API 密鑰（需要在 Zeabur 控制台設置）
  OPENAI_API_KEY:
    type: secret
    
  # 域名（Zeabur 自動設置）
  ZEABUR_DOMAIN:
    type: auto 